// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Unicon.Backend.WebApi.Context;

namespace Unicon.Backend.WebApi.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Unicon.Backend.WebApi.Entities.CommandsStoreEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CommandDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CommandType")
                        .HasColumnType("text");

                    b.Property<int>("RelatedCommandId")
                        .HasColumnType("integer");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CommandsStoreEntries");
                });

            modelBuilder.Entity("Unicon.Backend.WebApi.Entities.DeviceDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("DefinitionString")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdateDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.ToTable("DeviceDefinitions");
                });

            modelBuilder.Entity("Unicon.Backend.WebApi.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("DeviceDefinitionId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeviceDefinitionId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Unicon.Backend.WebApi.Entities.UpdateDeviceDefinitionCommand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("DefinitionString")
                        .HasColumnType("text");

                    b.Property<string>("TagsOneLine")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UpdateDeviceDefinitionCommands");
                });

            modelBuilder.Entity("Unicon.Backend.WebApi.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Unicon.Backend.WebApi.Entities.DeviceDefinition", b =>
                {
                    b.HasOne("Unicon.Backend.WebApi.Entities.Tag", null)
                        .WithMany("RelatedDeviceDefinitions")
                        .HasForeignKey("TagId");
                });

            modelBuilder.Entity("Unicon.Backend.WebApi.Entities.Tag", b =>
                {
                    b.HasOne("Unicon.Backend.WebApi.Entities.DeviceDefinition", null)
                        .WithMany("Tags")
                        .HasForeignKey("DeviceDefinitionId");
                });
#pragma warning restore 612, 618
        }
    }
}
